Option to match velvet to card color
erasels/CardMastery pull request #1
Opened 2023-04-26 11:00 UTC by GameboyJ

Added an option in the mod config to match the velvet on the mastered cards with the color of the card. This only works on basegame colors, so red, blue, green, purple, curse and colorless. The option is off by default, so that people who do not know about mod config don't have their mod changed without being asked.

2023-04-26 14:08 UTC, erasels commented
Cool contribution, thank you.

Could you please show some screenshots of specifically colorless, curse and purple. Those colors strike me as a bit... odd.
Purple is super saturated (while green is pretty dark), curse is very black and colorless looks piniksh? I think I'd like it more if it wer greyish like the card frame normally would be. 

One issue this has is that it will be incopmpatible with the texture repalcement mod, something I'll have to think about, maybe there's a way to check if it's active.

2023-04-26 23:42 UTC, GameboyJ commented
I decided to redo all the art again, using a new tool i found in the image editing software i use. Now they match better with each other. I also madethe curse back a bit lighter, the colorless back a bit darker and the watcher back a bit less saturated. I hope you like these, but if not i'll change them again.
![image](https://user-images.githubusercontent.com/79210504/234725034-1c382233-2cb2-40c7-a2f7-c058449a8853.png)

2023-04-27 06:18 UTC, erasels requested changes
Yeah, I like the redone art much more, thank you.

2023-04-27 06:18 UTC, erasels commented on pom.xml
> +        <Steam.path>D:/Games/Steam/steamapps</Steam.path>
Please don#t push the pom.xml change :P

2023-04-27 07:34 UTC, GameboyJ commented on pom.xml
> +        <Steam.path>D:/Games/Steam/steamapps</Steam.path>
oops, changed it back now

2023-04-27 09:08 UTC, erasels commented
Nice, I'll wait with merging this until Kio has a way to check if a texture was replaced by the Texture Replacer mod, so that I can keep compatibility.

I appreciate you taking the time to add to this mod :)

2024-04-09 20:37 UTC, JackRenoson commented
Updated to use the new Attack Art and fix the merge issues with the multiple card requirement option
I think this should be fine to be merged. I don't think Kio has added the feature to Texture Replacer, but it still should work, if people have this mod and your other texture replacer mod, it should show the other skin if colored velvet is turned off, and colored velvet for the basegame colors if it is on, and still the other one for modded colors

2024-04-10 16:13 UTC, merged

2024-04-10 21:01 UTC, erasels commented
Thank you, the new version with this is out now.